### ISSUE TITLE
Main example in readme.md is wrong

### ISSUE THREAD

**Issue by RoyBellingan** [dnsimple/dnsimple-php#78]
Currently is

$account_id = $whoami->account->id;

But should not be ?

$account_id = $whoami->user->id;

Also the 
$response = $client->domains->listDomains($account_id);
Returns

```
PHP Fatal error:  Uncaught Dnsimple\Exceptions\HttpException: Authentication failed in /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Exceptions/HttpException.php:28
Stack trace:
#0 /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Client.php(254): Dnsimple\Exceptions\HttpException::fromResponse()
#1 /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Client.php(166): Dnsimple\Client->request()
#2 /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Service/ClientService.php(33): Dnsimple\Client->get()
#3 /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Service/Domains.php(33): Dnsimple\Service\ClientService->get()
#4 /home/roy/Public/DomainRegister/test1.php(15): Dnsimple\Service\Domains->listDomains()
#5 {main}
  thrown in /home/roy/Public/DomainRegister/vendor/dnsimple/dnsimple/src/Dnsimple/Exceptions/HttpException.php on line 28

```

But I am not sure if I am just missing to have an actual account or, why is not working

**Comment by RoyBellingan** [comment]
Ok I was using the wrong token, no idea there where 2.
